---

- name: Get all enabled products
  theforeman.foreman.resource_info:
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    server_url: "https://localhost"
    validate_certs: false
    resource: products
    organization: "{{ organization }}"
  register: products
  tags:
    - satellite-configure
    - satellite-configure-contentviews

- name: Get all repositories
  theforeman.foreman.repository_info:
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    server_url: "https://localhost"
    validate_certs: false
    organization: "{{ organization }}"
    product: "{{ item }}"
  with_items: "{{ products | json_query('resources[?repository_count > `0`].name') }}"
  register: all_repos
  tags:
    - satellite-configure
    - satellite-configure-contentviews

- name: Get all repos
  ansible.builtin.set_fact:
    repos: "{{ (all_repos | json_query('results[*].repositories[*].{ name: name, product: product.name }')) }}"
    repos_clean: []

- name: Collapse lists
  with_items: "{{ repos }}"
  ansible.builtin.set_fact:
    repos_clean: "{{ repos_clean + [item] }}"

- name: Create Red Hat Content View # noqa: args[module]
  theforeman.foreman.content_view:
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    server_url: "https://localhost"
    validate_certs: false
    organization: "{{ organization }}"
    name: "Red Hat"
    repositories: "{{ repos_clean | json_query('[?starts_with(product, `Red Hat Enterprise Linux`)]') }}"
  register: cv_rh_changed
  tags:
    - satellite-configure
    - satellite-configure-contentviews

- name: Publish new version of Red Hat Content View # noqa: no-handler
  when: cv_rh_changed.changed
  theforeman.foreman.content_view_version:
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    server_url: "https://localhost"
    validate_certs: false
    organization: "{{ organization }}"
    content_view: "Red Hat"
    lifecycle_environments:
      - Library
  register: cv_rh_published
  tags:
    - satellite-configure
    - satellite-configure-contentviews

- name: Create EPEL Content View # noqa: args[module]
  theforeman.foreman.content_view:
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    server_url: "https://localhost"
    validate_certs: false
    organization: "{{ organization }}"
    name: "EPEL"
    solve_dependencies: true
    repositories: "{{ repos_clean | json_query('[?starts_with(product, `EPEL`)]') }}"
  register: cv_epel_changed
  tags:
    - satellite-configure
    - satellite-configure-contentviews

- name: Create EPEL filter
  theforeman.foreman.content_view_filter:
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    server_url: "https://localhost"
    validate_certs: false
    organization: "{{ organization }}"
    name: "included packages"
    content_view: EPEL
    filter_type: "rpm"
    inclusion: true
    rule_name: "none"
  register: cv_epel_changed_filter
  tags:
    - satellite-configure
    - satellite-configure-contentviews

- name: Publish new version of EPEL Content View # noqa: no-handler
  when: cv_epel_changed.changed or cv_epel_changed_filter.changed
  theforeman.foreman.content_view_version:
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    server_url: "https://localhost"
    validate_certs: false
    organization: "{{ organization }}"
    content_view: "EPEL"
    lifecycle_environments:
      - Library
  register: cv_epel_published
  tags:
    - satellite-configure
    - satellite-configure-contentviews

- name: Create Everything Content View # noqa: args[module]
  theforeman.foreman.content_view:
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    server_url: "https://localhost"
    validate_certs: false
    organization: "{{ organization }}"
    name: "Everything"
    components:
      - content_view: "Red Hat"
        latest: true
      - content_view: "EPEL"
        latest: true
    composite: true
  register: ccv_changed
  tags:
    - satellite-configure
    - satellite-configure-contentviews

- name: Publish new version of Everything Composite Content View # noqa: no-handler
  when: ccv_changed.changed or cv_epel_published.changed or cv_rh_published.changed
  theforeman.foreman.content_view_version: # noqa: jinja[invalid]
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    server_url: "https://localhost"
    validate_certs: false
    organization: "{{ organization }}"
    content_view: "Everything"
    lifecycle_environments: "{{ ['Library'] + (lifecycles | json_query('[].name')) }}"
  tags:
    - satellite-configure
    - satellite-configure-contentviews
