---

- name: Install R10k gem
  community.general.gem:
    name: r10k
    executable: '/opt/puppetlabs/puppet/bin/gem'
    user_install: false
  tags:
    - satellite-configure
    - satellite-configure-puppet

- name: Create a symbolic link
  ansible.builtin.file:
    src: /opt/puppetlabs/puppet/bin/r10k
    dest: /usr/bin/r10k
    owner: root
    group: root
    state: link
  tags:
    - satellite-configure
    - satellite-configure-puppet

- name: Clone modules
  ansible.builtin.git:
    repo: "https://github.com/JasonN3/puppet_modules.git"
    dest: /etc/puppetlabs/code/modules/
    version: "main"
  tags:
    - satellite-configure
    - satellite-configure-puppet

- name: Configure r10k
  when: puppet_sources is defined and puppet_sources != {}
  tags:
    - satellite-configure
    - satellite-configure-puppet
  block:
    - name: Write R10k configuration file
      ansible.builtin.template:
        src: "{{ role_path }}/templates/r10k.conf.j2"
        dest: /etc/puppetlabs/r10k.conf
        owner: puppet
        group: puppet
        mode: '0644'

    - name: Add pre-run command to puppet server
      community.general.ini_file:
        path: /etc/puppetlabs/puppet/puppet.conf
        section: agent
        option: prerun_command
        value: 'r10k deploy environment -p -c /etc/puppetlabs/r10k.conf'
        mode: '0644'

    - name: Initial sync # noqa: no-changed-when
      ansible.builtin.command:
        cmd: 'r10k deploy environment -p -c /etc/puppetlabs/r10k.conf'

- name: Sync Puppet modules
  theforeman.foreman.puppetclasses_import:
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    server_url: "https://localhost"
    validate_certs: false
    smart_proxy: "{{ ansible_fqdn }}"
  tags:
    - satellite-configure
    - satellite-configure-puppet
